//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aluno()
        {
            this.Empresa = new HashSet<Empresa>();
            this.Prova = new HashSet<Prova>();
        }
    
        public int Alu_ID { get; set; }
        public int Alu_Curso_Cur_ID { get; set; }
        public string Alu_Nome { get; set; }
        public int Alu_Matricula { get; set; }
        public int Alu_Serie { get; set; }
        public string Alu_Email { get; set; }
        public string Alu_Senha { get; set; }
        public System.DateTime Alu_DataCadastro { get; set; }
        public bool Alu_Situation { get; set; }
    
        public virtual Curso Curso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empresa> Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prova> Prova { get; set; }
    }
}
