//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Beneficio()
        {
            this.PessoaBeneficio = new HashSet<PessoaBeneficio>();
        }
    
        public int Ben_ID { get; set; }
        public string Ben_Nome { get; set; }
        public string Ben_Descricao { get; set; }
        public double Ben_Custo { get; set; }
        public bool Ben_Situation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PessoaBeneficio> PessoaBeneficio { get; set; }
    }
}
