//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroTreinamento
    {
        public int CT_ID { get; set; }
        public int CT_Pessoa_Pes_ID { get; set; }
        public int CT_Treinamento_Tre_ID { get; set; }
        public System.DateTime CT_DataCadastro { get; set; }
        public bool CT_Realizado { get; set; }
        public bool CT_Situation { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual Treinamento Treinamento { get; set; }
    }
}
