//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadoBancario
    {
        public int DB_ID { get; set; }
        public int DB_Pessoa_Pes_ID { get; set; }
        public string DB_Tipo { get; set; }
        public string DB_Numero { get; set; }
        public System.DateTime DB_DataCadastro { get; set; }
        public bool DB_Situation { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
