//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demissao
    {
        public int Dem_ID { get; set; }
        public int Dem_Pessoa_Pes_ID { get; set; }
        public System.DateTime Dem_Data { get; set; }
        public string Dem_Motivo { get; set; }
        public double Dem_Salario { get; set; }
        public bool Dem_Situation { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
