//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimentacao
    {
        public int Mov_ID { get; set; }
        public int Mov_Pessoa_Pes_ID { get; set; }
        public string Mov_Mudanca { get; set; }
        public System.DateTime Mov_Data { get; set; }
        public bool Mov_Situation { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
