//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota
    {
        public int Not_ID { get; set; }
        public int Not_Prova_Pro_ID { get; set; }
        public double Not_Nota { get; set; }
        public System.DateTime Not_DataCadastro { get; set; }
        public bool Not_Situation { get; set; }
    
        public virtual Prova Prova { get; set; }
    }
}
