//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaBeneficio
    {
        public int PB_ID { get; set; }
        public int PB_Pessoa_Pes_ID { get; set; }
        public int PB_Beneficio_Ben_ID { get; set; }
        public System.DateTime PB_DataCadastro { get; set; }
        public bool PB_Situation { get; set; }
    
        public virtual Beneficio Beneficio { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
