//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posicao
    {
        public int Pos_ID { get; set; }
        public int Pos_Pessoa_Pes_ID { get; set; }
        public int Pos_Cargo_Car_ID { get; set; }
        public int Pos_Setor_Set_ID { get; set; }
        public bool Pos_Situation { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Cargo Cargo1 { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Setor Setor { get; set; }
        public virtual Setor Setor1 { get; set; }
    }
}
