//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestaoAvaliacao
    {
        public int QA_ID { get; set; }
        public int QA_Avaliacao_Ava_ID { get; set; }
        public int QA_Questao_Que_ID { get; set; }
    
        public virtual Avaliacao Avaliacao { get; set; }
        public virtual Questao Questao { get; set; }
    }
}
