//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resposta
    {
        public int Res_ID { get; set; }
        public int Res_Aluno_Alu_ID { get; set; }
        public System.DateTime Res_DataEntrega { get; set; }
        public int Res_Setor1 { get; set; }
        public int Res_Setor2 { get; set; }
        public int Res_Setor3 { get; set; }
        public int Res_Setor4 { get; set; }
        public int Res_Setor5 { get; set; }
        public int Res_Cargo1 { get; set; }
        public int Res_Cargo2 { get; set; }
        public int Res_Cargo3 { get; set; }
        public int Res_Cargo4 { get; set; }
        public int Res_Cargo5 { get; set; }
        public int Res_Pessoa1 { get; set; }
        public int Res_Pessoa2 { get; set; }
        public int Res_Pessoa3 { get; set; }
        public int Res_Pessoa4 { get; set; }
        public int Res_Pessoa5 { get; set; }
        public int Res_DadoDependente1 { get; set; }
        public int Res_DadoDependente2 { get; set; }
        public int Res_DadoDependente3 { get; set; }
        public int Res_DadoDependente4 { get; set; }
        public int Res_DadoDependente5 { get; set; }
        public int Res_Benefício1 { get; set; }
        public int Res_Beneficio2 { get; set; }
        public int Res_Beneficio3 { get; set; }
        public int Res_Beneficio4 { get; set; }
        public int Res_Beneficio5 { get; set; }
        public int Res_BeneficioFuncionario1 { get; set; }
        public int Res_BeneficioFuncionario2 { get; set; }
        public int Res_BeneficioFuncionario3 { get; set; }
        public int Res_BeneficioFuncionario4 { get; set; }
        public int Res_BeneficioFuncionario5 { get; set; }
        public int Res_AvaliacaoFuncionario1 { get; set; }
        public int Res_AvaliacaoFuncionario2 { get; set; }
        public int Res_AvaliacaoFuncionario3 { get; set; }
        public int Res_AvaliacaoFuncionario4 { get; set; }
        public int Res_AvaliacaoFuncionario5 { get; set; }
        public int Res_Demissao1 { get; set; }
        public int Res_Demissao2 { get; set; }
        public int Res_Demissao3 { get; set; }
    
        public virtual Avaliacao Avaliacao { get; set; }
        public virtual Avaliacao Avaliacao1 { get; set; }
        public virtual Avaliacao Avaliacao2 { get; set; }
        public virtual Avaliacao Avaliacao3 { get; set; }
        public virtual Avaliacao Avaliacao4 { get; set; }
        public virtual Beneficio Beneficio { get; set; }
        public virtual Beneficio Beneficio1 { get; set; }
        public virtual Beneficio Beneficio2 { get; set; }
        public virtual Beneficio Beneficio3 { get; set; }
        public virtual Beneficio Beneficio4 { get; set; }
        public virtual Cargo Cargo { get; set; }
        public virtual Cargo Cargo1 { get; set; }
        public virtual Cargo Cargo2 { get; set; }
        public virtual Cargo Cargo3 { get; set; }
        public virtual Cargo Cargo4 { get; set; }
        public virtual DadoDependente DadoDependente { get; set; }
        public virtual DadoDependente DadoDependente1 { get; set; }
        public virtual DadoDependente DadoDependente2 { get; set; }
        public virtual DadoDependente DadoDependente3 { get; set; }
        public virtual DadoDependente DadoDependente4 { get; set; }
        public virtual Demissao Demissao { get; set; }
        public virtual Demissao Demissao1 { get; set; }
        public virtual Demissao Demissao2 { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Pessoa Pessoa1 { get; set; }
        public virtual Pessoa Pessoa2 { get; set; }
        public virtual Pessoa Pessoa3 { get; set; }
        public virtual Pessoa Pessoa4 { get; set; }
        public virtual PessoaBeneficio PessoaBeneficio { get; set; }
        public virtual PessoaBeneficio PessoaBeneficio1 { get; set; }
        public virtual PessoaBeneficio PessoaBeneficio2 { get; set; }
        public virtual PessoaBeneficio PessoaBeneficio3 { get; set; }
        public virtual PessoaBeneficio PessoaBeneficio4 { get; set; }
        public virtual Setor Setor { get; set; }
        public virtual Setor Setor1 { get; set; }
        public virtual Setor Setor2 { get; set; }
        public virtual Setor Setor3 { get; set; }
        public virtual Setor Setor4 { get; set; }
    }
}
