//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Notas
    {
        public string NomeAluno { get; set; }
        public int MatriculaAluno { get; set; }
        public string Curso { get; set; }
        public int SerieAluno { get; set; }
        public Nullable<int> CodigoProva { get; set; }
        public string Entregou { get; set; }
        public double NotaProva { get; set; }
    }
}
