//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Provas
    {
        public int CodigoProva { get; set; }
        public Nullable<int> QuantidadeProvas { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public System.DateTime DataTermino { get; set; }
    }
}
